# Project settings - General
version: 0.0.1
title: "Bottom Lines"
description: "A quarter-century report on Canada's natural security."
baseurl: ""
url: "http://project-name.thetyee.ca"
logo: 'tss_logo.png'

# Project settings - Analytics
analytics:
    ga_tracking_id: 'UA-12345-5'

# Project settings - Meta
author: "Tyee Solutions Society"
robots: "index, follow"
revisit: "1 day"
copyright: "&copy; The Tyee 2014"

# Project settings - Assets
asset_paths:
    img: ""
    js:  ""

# Project settings - URLs
urls:
    display: 'project-name.thetyee.ca'
    privacy: 'http://project-name.thetyee.ca/privacy_url'
    credits: 'http://project-name.thetyee.ca/credits_url'
    credits: 'http://github.com/TheTyee/project-name'

# Project settings - Social
social:
    facebook:
        fb_admins:
            - 12345
        og_url:
        og_image:
        og_sitename:
    twitter:
    gplus:

# Jekyll build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - bower.json
  - package.json
  - node_modules
  - bower_components
  - Gruntfile.js
  - gemfile
  - Gemfile.lock
  - _vendor
